### ISSUE TITLE
events for detection if swipe/drag started

### ISSUE THREAD

**Issue by mvanhelmont** [rhanb/nativescript-swipe-layout#5]
Nice plugin, is it also posible to fire a event when de swipping/draging is started en ended?

So we can display a text on a image like Tinder?

thanks

**Comment by rhanb** [comment]
@mvanhelmont  thanks

unfortunately the events are only triggered once swiping/dragging is done, but it could be implemented.
it could be a good feature for this plugin but not sure if I'll get time to implement that anytime soon, i encourage you to contribute and do a PR. It would be highly appreciated 😄

**Comment by abdullahkhalidmahmood** [comment]
Hi, when i click on button to do swipe right/left/up i receive an error for NS Angular: 
`CONSOLE ERROR: ERROR TypeError: Cannot read property 'animateSwipeLeft' of undefined
CONSOLE ERROR: ERROR TypeError: Cannot read property 'animateSwipeRight' of undefined
CONSOLE ERROR: ERROR TypeError: Cannot read property 'animateSwipeUp' of undefined`
