### ISSUE TITLE
Any plan to upgrade this plugin to align with the latest nativescript release?

### ISSUE THREAD

**Issue by jannomeister** [rhanb/nativescript-swipe-layout#6]

**Comment by rhanb** [comment]
Hello @jannomeister ,

Please describe the issues you're having with v6.

**Comment by zaretu** [comment]
Don't work with nativescript 7. Will there be an upgrade ? 
https://nativescript.org/blog/nativescript-7-for-plugin-authors/

**Comment by JayalaxmiAnchan** [comment]
Hi,
I am working in Nativescript 7.2.0. I am trying to use swipe layout in my project. The version of swipe layout plugin 1.0.5 is not supported in latest version of nativescript. Is there any solutions for this issue. It gives this kind of error while running it in android and Ios emulators.

![swipe_error](https://user-images.githubusercontent.com/78347936/109797154-11ba0e80-7be7-11eb-9ba1-6876f87caf86.png)

**Comment by rhanb** [comment]
Hello @JayalaxmiAnchan 
As the plugin hasn't been updated for a while, it doesn't work for the latest release of NativeScript.
NativeScript changed a lot of modules and their path, as you can see in the error, the plugin tries to import some modules that are not available anymore for the old path.
To fix this issue it would require changing all the paths of the imports inside the plugin source code to match the latest version of NativeScript.
I don't maintain this plugin anymore, but if you're willing to do those changes I'd be happy to merge a PR and publish a new version of the plugin on npm.

**Comment by Harshitha-suvarna1** [comment]
I also have the same issue with version of swipe layout. can you please help me with the changes that are required to make the swipe layout work.

**Comment by vijesh1998** [comment]
i also have same issue.can you help me to resolve this issue.

**Comment by rhanb** [comment]
Those imports must be updated:

https://github.com/rhanb/nativescript-swipe-layout/blob/master/src/swipe-layout.common.ts#L1

But I'm not even sure it will be enough, I'm myself pretty outdated on the changes made to NativeScript, there is a new plugin API I believe that I don't know much about.

As said above I don't actively maintain this plugin therefore don't expect me to fix this issue anytime soon.

**Comment by bradmartin** [comment]
https://github.com/rhanb/nativescript-swipe-layout/pull/7 here is the PR for NS7. Just needs to be published to NPM. Tested iOS and Android with the core demo app and it runs successfully.

**Comment by rhanb** [comment]
thanks for this one @bradmartin 👍🏻

**Comment by rhanb** [comment]
The package has been published to npm under version `2.0.0`
